/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guilhermeteixeira.comercio.view;

import guilhermeteixeira.comercio.modelo.Produto;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GUILHERME
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameCadastroProduto = new javax.swing.JInternalFrame();
        jLabelCadastroProdutoNome = new javax.swing.JLabel();
        jTextFieldCadastroProdutoNome = new javax.swing.JTextField();
        jLabelCadastroProdutoPreco = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPreco = new javax.swing.JTextField();
        jButtonCadastroProdutoSalvar = new javax.swing.JButton();
        jButtonCadastroProdutoCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroDeProduto = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoProduto = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarProduto = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro e Venda de Produtos");

        jInternalFrameCadastroProduto.setTitle("Cadastro de Produtos");
        jInternalFrameCadastroProduto.setVisible(true);

        jLabelCadastroProdutoNome.setText("Nome do Produto");

        jTextFieldCadastroProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroProdutoNomeActionPerformed(evt);
            }
        });

        jLabelCadastroProdutoPreco.setText("Preço");

        jButtonCadastroProdutoSalvar.setText("Salvar");
        jButtonCadastroProdutoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroProdutoCancelar.setText("Cancelar");
        jButtonCadastroProdutoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroProdutoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroProduto.getContentPane());
        jInternalFrameCadastroProduto.getContentPane().setLayout(jInternalFrameCadastroProdutoLayout);
        jInternalFrameCadastroProdutoLayout.setHorizontalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroProdutoNome)
                    .addComponent(jLabelCadastroProdutoPreco))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroProdutoSalvar)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCadastroProdutoCancelar))
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jInternalFrameCadastroProdutoLayout.setVerticalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCadastroProdutoNome)
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroProdutoPreco))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProdutoSalvar)
                    .addComponent(jButtonCadastroProdutoCancelar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFrameCadastroProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroProduto)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroProduto)
                .addContainerGap())
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroDeProduto.setText("Produto");
        jMenuItemCadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroDeProduto);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoProduto.setText("Produto");
        jMenuEdicao.add(jMenuItemEdicaoProduto);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarProduto.setText("Produto");
        jMenuPesquisar.add(jMenuItemPesquisarProduto);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeProdutoActionPerformed
      jInternalFrameCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroDeProdutoActionPerformed

    private void jTextFieldCadastroProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroProdutoNomeActionPerformed

    private void jButtonCadastroProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoCancelarActionPerformed
       jTextFieldCadastroProdutoNome.setText("");
       jTextFieldCadastroProdutoPreco.setText("");
        jInternalFrameCadastroProduto.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroProdutoCancelarActionPerformed

    private void jButtonCadastroProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoSalvarActionPerformed
       String nome = jTextFieldCadastroProdutoNome.getText();
      
       
       if (nome.equals("")){
      JOptionPane.showMessageDialog(rootPane, " O campo Nome do Produto esta Vazio");
      
    }//GEN-LAST:event_jButtonCadastroProdutoSalvarActionPerformed
       else {
       String preco = jTextFieldCadastroProdutoPreco.getText();
       if (preco.equals("")) {
           JOptionPane.showMessageDialog(rootPane, "O Campo Preço esta vazio");
       } else {
           try {
               double precoConvertido = Double.parseDouble(preco);
               Produto produto = new Produto(nome, precoConvertido);
               produto.apresentarProduto();
               
               
               
               jTextFieldCadastroProdutoNome.setText("");
               jTextFieldCadastroProdutoPreco.setText("");
                                    
               JOptionPane.showMessageDialog(rootPane, "O Produto "+nome+"! No Valor de: R$" +preco+ " Foi Cadastrado com Sucesso");
                                      
               jInternalFrameCadastroProduto.setVisible(false);
           }catch (Exception e){
                              JOptionPane.showMessageDialog(rootPane, "Neste Campo de Preço, não use virgulas separe com pontos");
           }
       }
       }
    }
    
   
      public JInternalFrame getJInternalFrameCadastroProduto(){
      return jInternalFrameCadastroProduto;
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroProdutoCancelar;
    private javax.swing.JButton jButtonCadastroProdutoSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroProduto;
    private javax.swing.JLabel jLabelCadastroProdutoNome;
    private javax.swing.JLabel jLabelCadastroProdutoPreco;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroDeProduto;
    private javax.swing.JMenuItem jMenuItemEdicaoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProduto;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JTextField jTextFieldCadastroProdutoNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoPreco;
    // End of variables declaration//GEN-END:variables
}
