/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guilhermeteixeira.comercio.view;

import guilhermeteixeira.comercio.modelo.Carrinho;
import guilhermeteixeira.comercio.modelo.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILHERME
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarID = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jInternalFrameCadastroProduto = new javax.swing.JInternalFrame();
        jLabelCadastroProdutoNome = new javax.swing.JLabel();
        jTextFieldCadastroProdutoNome = new javax.swing.JTextField();
        jLabelCadastroProdutoPreco = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPreco = new javax.swing.JTextField();
        jButtonCadastroProdutoSalvar = new javax.swing.JButton();
        jButtonCadastroProdutoCancelar = new javax.swing.JButton();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jLabelPesquisarQuantidade = new javax.swing.JLabel();
        jTextFieldPesquisarQuantidade = new javax.swing.JTextField();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroDeProduto = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoProduto = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarProduto = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro e Venda de Produtos");

        jInternalFrameEditarCadastro.setTitle("Edição De Cadastros");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome do Produto");

        jLabel4.setText("Preço");

        jLabel5.setText("ID:");

        jTextFieldEditarID.setEnabled(false);

        jButtonEditarSalvar.setText("Salvar");
        jButtonEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvarActionPerformed(evt);
            }
        });

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonEditarSalvar)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonEditarCancelar))
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEditarID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addGap(16, 16, 16))
        );

        jInternalFrameCadastroProduto.setTitle("Cadastro de Produtos");
        jInternalFrameCadastroProduto.setVisible(true);

        jLabelCadastroProdutoNome.setText("Nome do Produto");

        jTextFieldCadastroProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroProdutoNomeActionPerformed(evt);
            }
        });

        jLabelCadastroProdutoPreco.setText("Preço");

        jButtonCadastroProdutoSalvar.setText("Salvar");
        jButtonCadastroProdutoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroProdutoCancelar.setText("Cancelar");
        jButtonCadastroProdutoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroProdutoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroProduto.getContentPane());
        jInternalFrameCadastroProduto.getContentPane().setLayout(jInternalFrameCadastroProdutoLayout);
        jInternalFrameCadastroProdutoLayout.setHorizontalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroProdutoNome)
                    .addComponent(jLabelCadastroProdutoPreco))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                            .addComponent(jButtonCadastroProdutoSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastroProdutoCancelar))
                        .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jInternalFrameCadastroProdutoLayout.setVerticalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCadastroProdutoNome)
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProdutoPreco)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProdutoSalvar)
                    .addComponent(jButtonCadastroProdutoCancelar))
                .addGap(33, 33, 33))
        );

        jInternalFramePesquisar.setTitle("Pesquisar Por Nome");
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarPorNome);

        jLabel1.setText("Selecione a Ação Desejada");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir", "Adicionar No Carrinho", " " }));

        jLabel2.setText("Qual o ID do Produto");

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarConfirmarActionPerformed(evt);
            }
        });

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });

        jLabelPesquisarQuantidade.setText("Quantidade");

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPesquisarQuantidade))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarCancelar)
                        .addGap(27, 27, 27))
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisarQuantidade)
                    .addComponent(jTextFieldPesquisarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisarConfirmar)
                        .addComponent(jButtonPesquisarCancelar)))
                .addGap(12, 12, 12))
        );

        jDesktopPane1.setLayer(jInternalFrameEditarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameCadastroProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jInternalFrameCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(780, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(485, 485, 485)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(486, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jInternalFrameCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(460, 460, 460)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroDeProduto.setText("Produto");
        jMenuItemCadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroDeProduto);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoProduto.setText("Produto");
        jMenuItemEdicaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdicaoProdutoActionPerformed(evt);
            }
        });
        jMenuEdicao.add(jMenuItemEdicaoProduto);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarProduto.setText("Produto");
        jMenuItemPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarProdutoActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarProduto);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeProdutoActionPerformed
      jInternalFrameCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroDeProdutoActionPerformed

    private void jTextFieldCadastroProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroProdutoNomeActionPerformed

    private void jButtonCadastroProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoCancelarActionPerformed
       jTextFieldCadastroProdutoNome.setText("");
       jTextFieldCadastroProdutoPreco.setText("");
        jInternalFrameCadastroProduto.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroProdutoCancelarActionPerformed

    private void jButtonCadastroProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoSalvarActionPerformed
       String nome = jTextFieldCadastroProdutoNome.getText();
      
       
       if (nome.equals("")){
      JOptionPane.showMessageDialog(rootPane, " O campo Nome do Produto esta Vazio");
      
    }//GEN-LAST:event_jButtonCadastroProdutoSalvarActionPerformed
           else {
       String preco = jTextFieldCadastroProdutoPreco.getText();
       if (preco.equals("")) {
           JOptionPane.showMessageDialog(rootPane, "O Campo Preço esta vazio");
       } else {
           try {
               double precoConvertido = Double.parseDouble(preco);
               Produto produto = new Produto(nome, precoConvertido);
               produto.apresentarProduto();
               produto.salvar(nome, precoConvertido);
               
               
               jTextFieldCadastroProdutoNome.setText("");
               jTextFieldCadastroProdutoPreco.setText("");
                                    
               JOptionPane.showMessageDialog(rootPane, "O Produto "+nome+"! No Valor de: R$" +preco+ " Foi Cadastrado com Sucesso");
                                      
               jInternalFrameCadastroProduto.setVisible(false);
           }catch (Exception e){
                JOptionPane.showMessageDialog(rootPane, "Neste Campo de Preço, não use virgulas separe com pontos");
           }
       }
}
    }
    private void jMenuItemPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarProdutoActionPerformed
                         // TODO add your handling code here:
         String nome = JOptionPane.showInputDialog("Informe o Nome");
            Produto produto = new Produto();
            ArrayList<Produto> produtos = produto.pesquisar(nome);
            
           DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("nome");
            modelo.addColumn("preco");
            
            for (Produto produtoAux: produtos){
                modelo.addRow(new Object[]{produtoAux.getId(), produtoAux.getNome(), produtoAux.getPreco()});
                jTablePesquisarPorNome.setModel(modelo);
                
            }
            jInternalFramePesquisar.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemPesquisarProdutoActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
             // TODO add your handling code here:
              Produto produto = new Produto();
              Carrinho carrinho = new Carrinho();
        String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
          System.out.println("Opção selecionada:"+ opcao);
          
           int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
             System.out.println("ID Informado: "+idPesquisar);
             if (opcao.equals("Excluir")){
                  try {
                      produto.deletar(idPesquisar);
                  } catch (SQLException ex) {
                      Logger.getLogger(GUIMenu.class.getName()).log(Level.SEVERE, null, ex);
                  }
               JOptionPane.showMessageDialog(rootPane, "O Produto de ID: "+idPesquisar+" Foi Excluido com sucesso.");
                 
            
                jComboBoxPesquisarAcao.setSelectedIndex(0);
                jTextFieldPesquisarID.setText("");
                jTextFieldPesquisarQuantidade.setText("");
                jInternalFramePesquisar.setVisible(false);
             }else if (opcao.equals("Editar")){
             jInternalFramePesquisar.setVisible(false);
                        
             Produto produtoRecuperado = produto.buscarPorid(idPesquisar);
             
             jTextFieldEditarID.setText(idPesquisar+"");
             jTextFieldEditarNome.setText(produtoRecuperado.getNome());
             jTextFieldEditarPreco.setText(produtoRecuperado.getPreco()+"");
             jInternalFrameEditarCadastro.setVisible(true);
             }else if (opcao.equals("Adicionar No Carrinho")){   //sadiconar no carrinho
                 int id = Integer.parseInt(jTextFieldPesquisarID.getText());
                 int quantidade = Integer.parseInt(jTextFieldPesquisarQuantidade.getText());
                 
                   produto.adicionarCarrinho(id, quantidade);
                 
                JOptionPane.showMessageDialog(rootPane," O Produto foi Adicionado no Carrinho!");
                jTextFieldPesquisarID.setText("");
                jComboBoxPesquisarAcao.setSelectedIndex(0);
                jTextFieldPesquisarQuantidade.setText("");
                  jInternalFramePesquisar.setVisible(false);
;       }       
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        jInternalFramePesquisar.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
     try {
        // 1. Pega os dados digitados nos campos
        int id = Integer.parseInt(jTextFieldEditarID.getText());
        String nome = jTextFieldEditarNome.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());

        // 2. Chama o método de edição da classe Produto
        Produto produto = new Produto();
        produto.editar(nome, preco, id);

        // 3. Mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");

         jTextFieldEditarID.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        jInternalFrameEditarCadastro.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Preço ou ID inválido. Verifique os campos e se tiver virgula troque por ponto.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao editar o produto.");
    }

     
    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed

    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarID.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

    private void jMenuItemEdicaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoProdutoActionPerformed
                 String nome = JOptionPane.showInputDialog("Informe o Nome");
            Produto produto = new Produto();
            ArrayList<Produto> produtos = produto.pesquisar(nome);
            
           DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("nome");
            modelo.addColumn("preco");
            
            for (Produto produtoAux: produtos){
                modelo.addRow(new Object[]{produtoAux.getId(), produtoAux.getNome(), produtoAux.getPreco()});
                jTablePesquisarPorNome.setModel(modelo);
                
            }
            jInternalFramePesquisar.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemEdicaoProdutoActionPerformed
          public JInternalFrame getJInternalFrameEditarCadastro(){
              return jInternalFrameEditarCadastro;
          }  
    
    
      public JInternalFrame getJInternalFrameCadastroProduto(){
      return jInternalFrameCadastroProduto;
        }
         public JInternalFrame getJInternalFramePesquisar(){
             return jInternalFramePesquisar;
         }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroProdutoCancelar;
    private javax.swing.JButton jButtonCadastroProdutoSalvar;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroProduto;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastroProdutoNome;
    private javax.swing.JLabel jLabelCadastroProdutoPreco;
    private javax.swing.JLabel jLabelPesquisarQuantidade;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroDeProduto;
    private javax.swing.JMenuItem jMenuItemEdicaoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProduto;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoPreco;
    private javax.swing.JTextField jTextFieldEditarID;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldPesquisarID;
    private javax.swing.JTextField jTextFieldPesquisarQuantidade;
    // End of variables declaration//GEN-END:variables
}
