/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guilhermeteixeira.comercio.view;

import guilhermeteixeira.comercio.controle.Banco;
import guilhermeteixeira.comercio.modelo.Carrinho;
import guilhermeteixeira.comercio.modelo.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILHERME
 */
public class GUIMenu extends javax.swing.JFrame {
    // Declarar as variáveis aqui
    private String nome;
    private String codigobarras;
    private double valorcompra;
    private int estoque;
    private String fornecedor;
    private String telefone;
    private double preco;

    public GUIMenu() {
        initComponents();
    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameAdicionarCarrinho = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAdicionarProdutoNoCarrinho = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxAdicionarProdutoNoCarrinho = new javax.swing.JComboBox<>();
        jLabelAdicionarNoCarrinho = new javax.swing.JLabel();
        jTextFieldPesquisandoQuantidade = new javax.swing.JTextField();
        jLabelEntradaProduto = new javax.swing.JLabel();
        jTextFieldEntradaProduto = new javax.swing.JTextField();
        jButtonProcurarProduto = new javax.swing.JButton();
        jButtonConfirmarAdicionarParaCarrinho = new javax.swing.JButton();
        jButtonCancelarAdicionarProdutoParaCarrinho = new javax.swing.JButton();
        jInternalFrameCarrinho = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarrinho = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCarrinhoTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarID = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEditarValorCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEditarFornecedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEditarTelefoneForne = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldEditarEstoque = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldEditarCodigoBarras = new javax.swing.JTextField();
        jInternalFrameCadastroProduto = new javax.swing.JInternalFrame();
        jLabelCadastroProdutoNome = new javax.swing.JLabel();
        jTextFieldCadastroProdutoNome = new javax.swing.JTextField();
        jLabelCadastroProdutoPreco = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPreco = new javax.swing.JTextField();
        jButtonCadastroProdutoSalvar = new javax.swing.JButton();
        jButtonCadastroProdutoCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPrecoCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCadastroProdutoFornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCadastroProdutoTelefoneFornecedor = new javax.swing.JTextField();
        jTextFieldCadastroProdutoEstoque = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCadastroProdutoCodigoBarras = new javax.swing.JTextField();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jLabelPesquisarQuantidade = new javax.swing.JLabel();
        jTextFieldPesquisarQuantidade = new javax.swing.JTextField();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroDeProduto = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoProduto = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarProduto = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemAdiconarNoCarrinho = new javax.swing.JMenuItem();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro e Venda de Produtos");

        jInternalFrameAdicionarCarrinho.setTitle("Adiconar Produtos Para Carrinho (VENDAS R$)");
        jInternalFrameAdicionarCarrinho.setVisible(true);

        jTableAdicionarProdutoNoCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAdicionarProdutoNoCarrinho.setCellSelectionEnabled(true);
        jTableAdicionarProdutoNoCarrinho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableAdicionarProdutoNoCarrinhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(jTableAdicionarProdutoNoCarrinho);

        jLabel17.setText("Registrar Vendas Por:");

        jComboBoxAdicionarProdutoNoCarrinho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código de Barras", "ID", "Nome", " " }));
        jComboBoxAdicionarProdutoNoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdicionarProdutoNoCarrinhoActionPerformed(evt);
            }
        });

        jLabelAdicionarNoCarrinho.setText("Quantidade");

        jTextFieldPesquisandoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisandoQuantidadeActionPerformed(evt);
            }
        });

        jButtonProcurarProduto.setText("Procurar");
        jButtonProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarProdutoActionPerformed(evt);
            }
        });

        jButtonConfirmarAdicionarParaCarrinho.setText("Confirmar");
        jButtonConfirmarAdicionarParaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarAdicionarParaCarrinhoActionPerformed(evt);
            }
        });

        jButtonCancelarAdicionarProdutoParaCarrinho.setText("Cancelar");

        javax.swing.GroupLayout jInternalFrameAdicionarCarrinhoLayout = new javax.swing.GroupLayout(jInternalFrameAdicionarCarrinho.getContentPane());
        jInternalFrameAdicionarCarrinho.getContentPane().setLayout(jInternalFrameAdicionarCarrinhoLayout);
        jInternalFrameAdicionarCarrinhoLayout.setHorizontalGroup(
            jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEntradaProduto)
                            .addComponent(jLabel17))
                        .addGap(75, 75, 75)
                        .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAdicionarProdutoNoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                                .addComponent(jTextFieldEntradaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabelAdicionarNoCarrinho)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPesquisandoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButtonProcurarProduto)
                .addGap(74, 74, 74)
                .addComponent(jButtonConfirmarAdicionarParaCarrinho)
                .addGap(113, 113, 113)
                .addComponent(jButtonCancelarAdicionarProdutoParaCarrinho)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrameAdicionarCarrinhoLayout.setVerticalGroup(
            jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameAdicionarCarrinhoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jComboBoxAdicionarProdutoNoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEntradaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdicionarNoCarrinho)
                            .addComponent(jTextFieldPesquisandoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelEntradaProduto))
                .addGap(42, 42, 42)
                .addGroup(jInternalFrameAdicionarCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProcurarProduto)
                    .addComponent(jButtonConfirmarAdicionarParaCarrinho)
                    .addComponent(jButtonCancelarAdicionarProdutoParaCarrinho))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jInternalFrameCarrinho.setTitle("Carrinho");
        jInternalFrameCarrinho.setVisible(true);

        jTableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableCarrinho);

        jLabel6.setText("Total R$");

        jTextFieldCarrinhoTotal.setEditable(false);

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCarrinhoLayout = new javax.swing.GroupLayout(jInternalFrameCarrinho.getContentPane());
        jInternalFrameCarrinho.getContentPane().setLayout(jInternalFrameCarrinhoLayout);
        jInternalFrameCarrinhoLayout.setHorizontalGroup(
            jInternalFrameCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCarrinhoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCarrinhoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldCarrinhoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(21, 21, 21))))
        );
        jInternalFrameCarrinhoLayout.setVerticalGroup(
            jInternalFrameCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCarrinhoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(jInternalFrameCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextFieldCarrinhoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23))
        );

        jInternalFrameEditarCadastro.setTitle("Edição De Cadastros");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome do Produto");

        jLabel4.setText("Preço");

        jLabel5.setText("ID:");

        jTextFieldEditarID.setEnabled(false);
        jTextFieldEditarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditarIDActionPerformed(evt);
            }
        });

        jButtonEditarSalvar.setText("Salvar");
        jButtonEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvarActionPerformed(evt);
            }
        });

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancelarActionPerformed(evt);
            }
        });

        jLabel10.setText("Preço de Compra");

        jLabel11.setText("Fornecedor");

        jLabel12.setText("Telefone/Fornecedor");

        jLabel14.setText("Estoque");

        jLabel16.setText("Código de Barras");

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldEditarValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel14)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldEditarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEditarTelefoneForne, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel11)))
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                                        .addComponent(jButtonEditarSalvar)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButtonEditarCancelar))
                                    .addComponent(jTextFieldEditarID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEditarFornecedor)
                                    .addComponent(jTextFieldEditarNome)
                                    .addComponent(jTextFieldEditarCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEditarCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEditarCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEditarValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldEditarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldEditarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldEditarTelefoneForne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jInternalFrameCadastroProduto.setTitle("Cadastro de Produtos");
        jInternalFrameCadastroProduto.setVisible(true);

        jLabelCadastroProdutoNome.setText("Nome do Produto");

        jTextFieldCadastroProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroProdutoNomeActionPerformed(evt);
            }
        });

        jLabelCadastroProdutoPreco.setText("Preço Venda");

        jButtonCadastroProdutoSalvar.setText("Salvar");
        jButtonCadastroProdutoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroProdutoCancelar.setText("Cancelar");
        jButtonCadastroProdutoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Preço de Compra");

        jLabel8.setText("Fornecedor");

        jTextFieldCadastroProdutoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroProdutoFornecedorActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefone Fornec.");

        jLabel13.setText("Estoque");

        jLabel15.setText("Código de Barras");

        javax.swing.GroupLayout jInternalFrameCadastroProdutoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroProduto.getContentPane());
        jInternalFrameCadastroProduto.getContentPane().setLayout(jInternalFrameCadastroProdutoLayout);
        jInternalFrameCadastroProdutoLayout.setHorizontalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCadastroProdutoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addGap(32, 32, 32)
                                    .addComponent(jTextFieldCadastroProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabelCadastroProdutoNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCadastroProdutoNome)
                                        .addGap(2, 2, 2))
                                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabelCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(23, 23, 23)
                                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCadastroProdutoTelefoneFornecedor)
                                            .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCadastroProdutoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCadastroProdutoCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(102, 102, 102))
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButtonCadastroProdutoSalvar)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonCadastroProdutoCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jInternalFrameCadastroProdutoLayout.setVerticalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProdutoNome)
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCadastroProdutoCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroProdutoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCadastroProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCadastroProdutoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCadastroProdutoTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProdutoPreco)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProdutoSalvar)
                    .addComponent(jButtonCadastroProdutoCancelar))
                .addGap(23, 23, 23))
        );

        jInternalFramePesquisar.setTitle("  Nessa Tela de Pesquisa   Pode Excluir um Tipo de  Produto    Editar Abre a Janela para Edição de Campo ou Item     Ou Cancelar e Sair");
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisarPorNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTablePesquisarPorNome.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTablePesquisarPorNome);
        jTablePesquisarPorNome.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("Selecione a Ação Desejada");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir" }));

        jLabel2.setText("Qual o ID do Produto");

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarConfirmarActionPerformed(evt);
            }
        });

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });

        jLabelPesquisarQuantidade.setText("Quantidade");

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPesquisarQuantidade))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarCancelar)
                        .addGap(27, 27, 27))
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPesquisarAcao, 0, 191, Short.MAX_VALUE)
                            .addComponent(jTextFieldPesquisarID))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisarConfirmar)
                        .addComponent(jButtonPesquisarCancelar))
                    .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPesquisarQuantidade)
                        .addComponent(jTextFieldPesquisarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jDesktopPane1.setLayer(jInternalFrameAdicionarCarrinho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameCarrinho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameEditarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameCadastroProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrameCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jInternalFrameAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jInternalFrameCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(485, 485, 485)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(486, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrameCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jInternalFrameCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jInternalFrameAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(460, 460, 460)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroDeProduto.setText("Produto");
        jMenuItemCadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroDeProduto);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoProduto.setText("Produto");
        jMenuItemEdicaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdicaoProdutoActionPerformed(evt);
            }
        });
        jMenuEdicao.add(jMenuItemEdicaoProduto);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarProduto.setText("Produto");
        jMenuItemPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarProdutoActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarProduto);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });

        jMenuItemAdiconarNoCarrinho.setText("Adicionar No Carrinho");
        jMenuItemAdiconarNoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdiconarNoCarrinhoActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemAdiconarNoCarrinho);

        jMenuItemVendasCarrinho.setText("Pagamento / Carrinho");
        jMenuItemVendasCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasCarrinhoActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeProdutoActionPerformed
      jInternalFrameCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroDeProdutoActionPerformed

    private void jTextFieldCadastroProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroProdutoNomeActionPerformed

    private void jButtonCadastroProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoCancelarActionPerformed
       jTextFieldCadastroProdutoNome.setText("");
       jTextFieldCadastroProdutoPrecoCompra.setText("");
       jTextFieldCadastroProdutoEstoque.setText("");
       jTextFieldCadastroProdutoFornecedor.setText("");
       jTextFieldCadastroProdutoTelefoneFornecedor.setText("");
       jTextFieldCadastroProdutoPreco.setText("");
        jInternalFrameCadastroProduto.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroProdutoCancelarActionPerformed

    private void jButtonCadastroProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoSalvarActionPerformed
            String nome = jTextFieldCadastroProdutoNome.getText();
            String codigobarras = jTextFieldCadastroProdutoCodigoBarras.getText();
            String precoStr = jTextFieldCadastroProdutoPreco.getText();
            String estoqueStr = jTextFieldCadastroProdutoEstoque.getText();
            String valorcompraStr = jTextFieldCadastroProdutoPrecoCompra.getText();
            String fornecedor = jTextFieldCadastroProdutoFornecedor.getText();
            String telefone = jTextFieldCadastroProdutoTelefoneFornecedor.getText();

if (nome.isEmpty() || codigobarras.isEmpty() || precoStr.isEmpty() || valorcompraStr.isEmpty() || estoqueStr.isEmpty() || fornecedor.isEmpty() || telefone.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
} else {
    try {
        double preco = Double.parseDouble(precoStr);
        double valorcompra = Double.parseDouble(valorcompraStr);
        int estoque;
        try{
            estoque = Integer.parseInt(estoqueStr);
           } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, " O Campo Estoque deve converter apenas Números Inteiros.");
            return;
        }
        Produto produto = new Produto(nome, codigobarras, valorcompra, estoque, fornecedor, telefone, preco);

        Banco b = new Banco();
        Connection conexao = b.conectar();
        b.salvar(produto, conexao);

        jTextFieldCadastroProdutoNome.setText("");
        jTextFieldCadastroProdutoCodigoBarras.setText("");
        jTextFieldCadastroProdutoPreco.setText("");
        jTextFieldCadastroProdutoPrecoCompra.setText("");
        jTextFieldCadastroProdutoEstoque.setText("");
        jTextFieldCadastroProdutoFornecedor.setText("");
        jTextFieldCadastroProdutoTelefoneFornecedor.setText("");

        JOptionPane.showMessageDialog(rootPane, "O Produto " + nome + " no valor de R$ " + preco + " foi cadastrado com sucesso!");
       // foi fechado por enquanto 14/10/25 jInternalFrameCadastroProduto.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: Use ponto (.) no lugar de vírgula nos campos de preço.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro ao salvar o produto: " + e.getMessage());
    }
}
            
    }//GEN-LAST:event_jButtonCadastroProdutoSalvarActionPerformed
                                
           
    private void jMenuItemPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarProdutoActionPerformed
                         // TODO add your handling code here:
         String nome = JOptionPane.showInputDialog("Informe o Nome");
            Produto produto = new Produto(nome, codigobarras, valorcompra, estoque, fornecedor, telefone, preco);
            ArrayList<Produto> produtos = produto.pesquisar(nome);
            
           DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nome");
            modelo.addColumn("CoditoBarras");
            modelo.addColumn("ValorCompra");
             modelo.addColumn("Estoque");
            modelo.addColumn("Fornecedor");
            modelo.addColumn("Telefone");
            modelo.addColumn("Preco");
            for (Produto produtoAux: produtos){
                modelo.addRow(new Object[]{produtoAux.getId(), produtoAux.getNome(), produtoAux.getCodigoBarras(), produtoAux.getValorCompra(), produtoAux.getEstoque(), produtoAux.getFornecedor(), produtoAux.getTelefoneForne(), produtoAux.getPreco(),});
                jTablePesquisarPorNome.setModel(modelo);
                
            }
            jInternalFramePesquisar.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemPesquisarProdutoActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
             // TODO add your handling code here:
              Produto produto = new Produto(nome, codigobarras, valorcompra, estoque, fornecedor, telefone, preco);
              Carrinho carrinho = new Carrinho();
        String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
          System.out.println("Opção selecionada:"+ opcao);
            
             int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
             System.out.println("ID Informado: "+idPesquisar);
             if (opcao.equals("Excluir")){
                  try {
                      produto.deletar(idPesquisar);
                  } catch (SQLException ex) {
                      Logger.getLogger(GUIMenu.class.getName()).log(Level.SEVERE, null, ex);
                  }
               JOptionPane.showMessageDialog(rootPane, "O Produto de ID: "+idPesquisar+" Foi Excluido com sucesso.");
                 
               
                jComboBoxPesquisarAcao.setSelectedIndex(0);
                jTextFieldPesquisarID.setText("");
             //   jTextFieldPesquisarQuantidade.setText("");
                jInternalFramePesquisar.setVisible(false);
             }else if (opcao.equals("Editar")){
               jInternalFramePesquisar.setVisible(false);
           carregarCamposParaEdicao(idPesquisar); // <-- AQUI VOCÊ CHAMA O MÉTODO COMPLETO
           jInternalFrameEditarCadastro.setVisible(true);

            // }else if (opcao.equals("Adicionar No Carrinho")){   //sadiconar no carrinho
              //   int id = Integer.parseInt(jTextFieldPesquisarID.getText());
              //   int quantidade = Integer.parseInt(jTextFieldPesquisarQuantidade.getText());
                 
              //     produto.adicionarCarrinho(id, quantidade);
                 
              //  JOptionPane.showMessageDialog(rootPane," O Produto foi Adicionado no Carrinho!");
              //  jTextFieldPesquisarID.setText("");
              //  jComboBoxPesquisarAcao.setSelectedIndex(0);
             //   jTextFieldPesquisarQuantidade.setText("");
             //   jInternalFramePesquisar.setVisible(false);
       }       
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        jInternalFramePesquisar.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
       try {
        // 1. Pega os dados digitados nos campos
        int id = Integer.parseInt(jTextFieldEditarID.getText());
        String nome = jTextFieldEditarNome.getText();
        String codigobarras = jTextFieldEditarCodigoBarras.getText();
        double valorcompra = Double.parseDouble(jTextFieldEditarValorCompra.getText());
        int estoque = Integer.parseInt(jTextFieldEditarEstoque.getText());
        String fornecedor = jTextFieldEditarFornecedor.getText();
        String telefone = jTextFieldEditarTelefoneForne.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());

        // 2. Atualiza o produto chamando o método editar da classe Produto
        Produto produto = new Produto();
        produto.editar(nome, codigobarras, valorcompra, estoque, fornecedor, telefone, preco, id);

        // 3. Mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");

        // 4. Limpa os campos e fecha a janela de edição
        jTextFieldEditarID.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarCodigoBarras.setText("");
        jTextFieldEditarValorCompra.setText("");
        jTextFieldEditarEstoque.setText("");
        jTextFieldEditarFornecedor.setText("");
        jTextFieldEditarTelefoneForne.setText("");
        jTextFieldEditarPreco.setText("");

        jInternalFrameEditarCadastro.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Preço ou ID inválido. Verifique os campos e se tiver vírgula troque por ponto.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao editar o produto.");
    }

    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed
       
         public void carregarCamposParaEdicao(int idProduto) {
    Produto produto = new Produto();
    Produto encontrado = produto.buscarPorId(idProduto);

    if (encontrado != null) {
        jTextFieldEditarID.setText(String.valueOf(encontrado.getId()));
        jTextFieldEditarNome.setText(encontrado.getNome());
        jTextFieldEditarCodigoBarras.setText(encontrado.getCodigoBarras());
        jTextFieldEditarValorCompra.setText(String.valueOf(encontrado.getValorCompra()));
        jTextFieldEditarEstoque.setText(String.valueOf(encontrado.getEstoque()));
        jTextFieldEditarFornecedor.setText(encontrado.getFornecedor());
        jTextFieldEditarTelefoneForne.setText(encontrado.getTelefoneForne());
        jTextFieldEditarPreco.setText(String.valueOf((double) encontrado.getPreco()));
    } else {
        JOptionPane.showMessageDialog(this, "Produto não encontrado!");
    }
}
    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarID.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarCodigoBarras.setText("");
        jTextFieldEditarValorCompra.setText("");
        jTextFieldEditarEstoque.setText("");
        jTextFieldEditarFornecedor.setText("");
        jTextFieldEditarTelefoneForne.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

    private void jMenuItemEdicaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoProdutoActionPerformed
        String nome = JOptionPane.showInputDialog("Informe o nome do produto que deseja editar:");

    if (nome != null && !nome.trim().isEmpty()) {
          Produto produto = new Produto();
        ArrayList<Produto> produtos = produto.pesquisar(nome);

        if (produtos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum produto encontrado com o nome: " + nome);
        } else {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nome");
             modelo.addColumn("CodigoBarras");
            modelo.addColumn("ValorCompra");
            modelo.addColumn("Estoque");
            modelo.addColumn("Fonecedor");
            modelo.addColumn("TelefoneForne");
            modelo.addColumn("Preço");

            for (Produto p : produtos) {
                modelo.addRow(new Object[]{p.getId(), p.getNome(), p.getCodigoBarras(), p.getValorCompra(), p.getEstoque(), p.getFornecedor(), p.getTelefoneForne(), p.getPreco()});
                jTablePesquisarPorNome.setModel(modelo);
               jInternalFramePesquisar.setVisible(true);
            }
           }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Digite um nome válido.");
    }
    }//GEN-LAST:event_jMenuItemEdicaoProdutoActionPerformed

    private void jMenuItemVendasCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasCarrinhoActionPerformed
           Produto produto = new Produto();
           HashMap<Produto, Integer> carrinho = produto.recuperarCarrinho();
            
           DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nome");
            modelo.addColumn("Preco");
            modelo.addColumn("Quantidade");
             
            for (Map.Entry<Produto, Integer> item: carrinho.entrySet()){
                Produto p = item.getKey();
               int quantidade = item.getValue();
                modelo.addRow(new Object[]{p.getId(), p.getNome(), p.getPreco()});
                jTableCarrinho.setModel(modelo);
                        }
            // jTextFieldCarrinhoTotal.setText(total+"");
             
            jInternalFrameCarrinho.setVisible(true);                          
    }//GEN-LAST:event_jMenuItemVendasCarrinhoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldCadastroProdutoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroProdutoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroProdutoFornecedorActionPerformed

    private void jTextFieldEditarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditarIDActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        // TODO dd your handling code here:
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuItemAdiconarNoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdiconarNoCarrinhoActionPerformed
        // TODO add your handling code here:.
         jInternalFrameAdicionarCarrinho.setVisible(true);
    }//GEN-LAST:event_jMenuItemAdiconarNoCarrinhoActionPerformed

    private void jTextFieldPesquisandoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisandoQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisandoQuantidadeActionPerformed

    private void jButtonConfirmarAdicionarParaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarAdicionarParaCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmarAdicionarParaCarrinhoActionPerformed

    private void jButtonProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarProdutoActionPerformed
  
        Banco banco = new Banco();
        String opcao = jComboBoxAdicionarProdutoNoCarrinho.getSelectedItem().toString();
         String entrada = jTextFieldEntradaProduto.getText().trim();
         Produto produtoEncontrado = null;

           if (opcao.equalsIgnoreCase("ID")) {
             try {
            int id = Integer.parseInt(entrada);
            produtoEncontrado = banco.buscarProdutoPorId(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
            return;
        }
    } else if (opcao.equalsIgnoreCase("Nome")) {
        produtoEncontrado = banco.buscarProdutoPorNomeExato(entrada);
    } else if (opcao.equalsIgnoreCase("Código de Barras")) {
        produtoEncontrado = banco.buscarProdutoPorCodigoBarras(entrada);
    }

    if (produtoEncontrado != null) {
        DefaultTableModel modelo = (DefaultTableModel) jTableAdicionarProdutoNoCarrinho.getModel();
        modelo.addRow(new Object[]{
            produtoEncontrado.getId(),
            produtoEncontrado.getNome(),
            produtoEncontrado.getCodigoBarras(),
            produtoEncontrado.getPreco()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Produto não encontrado.");
    }

    }//GEN-LAST:event_jButtonProcurarProdutoActionPerformed

    private void jTableAdicionarProdutoNoCarrinhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableAdicionarProdutoNoCarrinhoAncestorAdded
        // TODO add your handling code here:
            DefaultTableModel modeloTabelaCarrinho = new DefaultTableModel(
    new Object[]{"ID", "Nome", "Código de Barras", "Preço"}, 0
);
      jTableAdicionarProdutoNoCarrinho.setModel(modeloTabelaCarrinho);

    }//GEN-LAST:event_jTableAdicionarProdutoNoCarrinhoAncestorAdded

    private void jComboBoxAdicionarProdutoNoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdicionarProdutoNoCarrinhoActionPerformed
        // TODO add your handling code here:
       String opcao = jComboBoxAdicionarProdutoNoCarrinho.getSelectedItem().toString();

    if (opcao.equalsIgnoreCase("ID")) {
        jLabelEntradaProduto.setText("Digite o ID:");
    } else if (opcao.equalsIgnoreCase("Nome")) {
        jLabelEntradaProduto.setText("Digite o Nome:");
    } else if (opcao.equalsIgnoreCase("Código de Barras")) {
        jLabelEntradaProduto.setText("Digite o Código de Barras:");
    }

    jTextFieldEntradaProduto.setText(""); // Limpa campo sempre que mudar a opção

    }//GEN-LAST:event_jComboBoxAdicionarProdutoNoCarrinhoActionPerformed
          public JInternalFrame getJInternalFrameEditarCadastro(){
              return jInternalFrameEditarCadastro;
          }  
    
    
      public JInternalFrame getJInternalFrameCadastroProduto(){
      return jInternalFrameCadastroProduto;
        }
                    
         public JInternalFrame getJInternalFramePesquisar(){
             return jInternalFramePesquisar;
         }
         
         public JInternalFrame getJInternalFrameCarrinho(){
             return jInternalFrameCarrinho;
         }
         public javax.swing.JInternalFrame getJInternalFrameAdicionarCarrinho() {
      return jInternalFrameAdicionarCarrinho;
}
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastroProdutoCancelar;
    private javax.swing.JButton jButtonCadastroProdutoSalvar;
    private javax.swing.JButton jButtonCancelarAdicionarProdutoParaCarrinho;
    private javax.swing.JButton jButtonConfirmarAdicionarParaCarrinho;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JButton jButtonProcurarProduto;
    private javax.swing.JComboBox<String> jComboBoxAdicionarProdutoNoCarrinho;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameAdicionarCarrinho;
    private javax.swing.JInternalFrame jInternalFrameCadastroProduto;
    private javax.swing.JInternalFrame jInternalFrameCarrinho;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdicionarNoCarrinho;
    private javax.swing.JLabel jLabelCadastroProdutoNome;
    private javax.swing.JLabel jLabelCadastroProdutoPreco;
    private javax.swing.JLabel jLabelEntradaProduto;
    private javax.swing.JLabel jLabelPesquisarQuantidade;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemAdiconarNoCarrinho;
    private javax.swing.JMenuItem jMenuItemCadastroDeProduto;
    private javax.swing.JMenuItem jMenuItemEdicaoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProduto;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAdicionarProdutoNoCarrinho;
    private javax.swing.JTable jTableCarrinho;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoCodigoBarras;
    private javax.swing.JTextField jTextFieldCadastroProdutoEstoque;
    private javax.swing.JTextField jTextFieldCadastroProdutoFornecedor;
    private javax.swing.JTextField jTextFieldCadastroProdutoNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoPreco;
    private javax.swing.JTextField jTextFieldCadastroProdutoPrecoCompra;
    private javax.swing.JTextField jTextFieldCadastroProdutoTelefoneFornecedor;
    private javax.swing.JTextField jTextFieldCarrinhoTotal;
    private javax.swing.JTextField jTextFieldEditarCodigoBarras;
    private javax.swing.JTextField jTextFieldEditarEstoque;
    private javax.swing.JTextField jTextFieldEditarFornecedor;
    private javax.swing.JTextField jTextFieldEditarID;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldEditarTelefoneForne;
    private javax.swing.JTextField jTextFieldEditarValorCompra;
    private javax.swing.JTextField jTextFieldEntradaProduto;
    private javax.swing.JTextField jTextFieldPesquisandoQuantidade;
    private javax.swing.JTextField jTextFieldPesquisarID;
    private javax.swing.JTextField jTextFieldPesquisarQuantidade;
    // End of variables declaration//GEN-END:variables

   private boolean isEmpty() {
    return jTextFieldCadastroProdutoCodigoBarras.getText().trim().isEmpty();
}

   }
